name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout another repo
        uses: actions/checkout@v2
        with:
          repository: TechIsFun/SlidingSwitch
          
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Ensure .gitignore exists
        run: touch .gitignore
        
      - name: Add node_modules to .gitignore
        run: grep -qxF 'node_modules' .gitignore || echo 'node_modules' >> .gitignore
        
      - name: Debug content of .gitignore
        run: cat .gitignore
          
      - name: Install Husky
        run: npm install husky --save-dev

      - name: Setup Husky
        run: |
          npm set-script prepare "husky install"
          npm run prepare
          
      - name: Add pre-commit hook
        run: |
          npx husky add .husky/pre-commit "echo \"sample hook\""
          git add .husky/pre-commit
          
      - name: Debug content of repo
        run: ls

      - name: Debug changed files
        run: git status

      - name: Debug content of pre-commit
        run: |
          cat .husky/pre-commit
          
      - name: Get base branch for PR
        run: |
          echo BASE_BRANCH=`git checkout develop &> /dev/null && echo "develop" || git branch --show-current` >> $GITHUB_ENV
        
      - name: Delete node_modules before PR
        run: rm -rf node_modules
        
      - name: Commit changes
        run: |
          git config --global user.email "maintainer@example.com"
          git config --global user.name "Maintainer"
          git checkout -b husky
          git add -A
          git commit -a -m "chore: setup husky"
          git push --set-upstream origin husky
        
      - name: Create Pull Request
        run: |
          curl -X POST \
          -H 'Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}' \
          -H 'content-type: application/json' \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/TechIsFun/SlidingSwitch/pulls \
          --data '{
            "head": "husky",
            "base": "${{ env.BASE_BRANCH }}",
            "title": "Automated PR for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }'
          --fail

