name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout another repo
        uses: actions/checkout@v2
        with:
          repository: TechIsFun/SlidingSwitch
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Ensure .gitignore exists
        run: touch .gitignore
        
      - name: Add node_modules to .gitignore
        run: grep -qxF 'node_modules' .gitignore || echo 'node_modules' >> .gitignore
        
      - name: Debug content of .gitignore
        run: cat .gitignore
          
      - name: Install Husky
        run: npm install husky --save-dev

      - name: Setup Husky
        run: |
          npm set-script prepare "husky install"
          npm run prepare
          
      - name: Add pre-commit hook
        run: |
          npx husky add .husky/pre-commit "echo \"sample hook\""
          git add .husky/pre-commit
          
      - name: Debug content of repo
        run: ls

      - name: Debug changed files
        run: git status

      - name: Debug content of pre-commit
        run: |
          cat .husky/pre-commit
          
      - name: Get base branch for PR
        run: |
          echo BASE_BRANCH=`git checkout develop &> /dev/null && echo "develop" || git branch --show-current` >> $GITHUB_ENV
        
      - name: Delete node_modules before PR
        run: rm -rf node_modules
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: TechIsFun/SlidingSwitch
          commit-message: "chore: configure husky for git hooks"
          title: Configure Husky
          body: This PR will add husky with a default hook
          committer: GitHub <noreply@github.com>
          author: maintainer <maintainer@users.noreply.github.com>
          branch: husky
          base: ${{ env.BASE_BRANCH }}
          assignees: techisfun
          reviewers: techisfun
