name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout another repo
        uses: actions/checkout@v2
        with:
          repository: TechIsFun/iata-parser
          
      - name: Install npm 7
        run: npm i -g npm@7 --registry=https://registry.npmjs.org
        
      - name: Install Husky
        run: npm install husky -D

      - name: Setup prepare step
        run: |
          npm set-script prepare "husky install"
          npm run prepare
          
      - name: Add build hook
        run: |
          npx husky add .husky/pre-commit "./gradlew build"
          git add .husky/pre-commit
          
      - name: Debug content of pre-commit
        run: |
          cat .husky/pre-commit

