name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout another repo
        uses: actions/checkout@v2
        with:
          repository: TechIsFun/iata-parser
          
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Ensure .gitignore exists
        run: touch .gitignore
        
      - name: Add node_modules to .gitignore
        run: grep -qxF 'node_modules' .gitignore || echo 'node_modules' >> .gitignore
          
      - name: Install Husky
        run: npm install husky --save-dev

      - name: Setup Husky
        run: |
          npm set-script prepare "husky install"
          npm run prepare
          
      - name: Add pre-commit hook
        run: |
          npx husky add .husky/pre-commit "./gradlew build"
          git add .husky/pre-commit
          
      - name: Debug content of repo
        run: ls

      - name: Debug changed files
        run: git status

      - name: Debug content of pre-commit
        run: |
          cat .husky/pre-commit

